### PR TITLE
Put is_bad_pr into automerge failed reason

### PR DESCRIPTION
**Pull request by mkrizek**
Fixes https://github.com/ansible/ansibullbot/issues/998

### CODE REVIEW

**Comment by gundalow** [comment]
I think it's fine that any PR that triggers `too many files or commits` should have to be dealt with manually.

**Comment by mkrizek** [comment]
> I think it's fine that any PR that triggers too many files or commits should have to be dealt with manually.

Agreed. That's why I just wanted to put the info to bot_status, stating that even if the PR has enough shipits for automerge, the actual reason preventing automerge is `too many files or commits` and not `automerge shipit test failed`. Then someone should check the PR and merge manually. Putting that info into a comment might suggest that the submitter should open a new PR?

**Comment by mkrizek** [comment]
@pilou- thoughts?

**Comment by pilou-** [comment]
Because more than 50 files were modified by this PR, this PR was labeled with `needs_revision`.
When a PR is labeled with `needs_revision`, `shipit` comments are ignored (this is a good thing). Then it is impossible for such PR to be labeled with `shipit`. Such PR can not be _automerged_ because they lack `shipit` label.

My thoughts: 
- the bot should at least  add a specific comment explaining why the `needs_revision` label has been added (something like that https://github.com/ansible/ansible/pull/44377#issuecomment-414235496 : `this PR updates more than 50 files, such PR can only be merged by human, ask a human to review this PR`)
- should `shipit` comments override `needs_revision` label (meaning: add `shipit` label even when PR is already labeled with `needs_revision` due to 50+ updated files) ? should these PRs be automerged ?
  -> I say no to both. This would only benefit pull-requests updating more than 50 **community only** supported files : because if at least one file isn't community supported, automerge doesn't apply and merge must be performed by a human.

**Comment by gundalow** [comment]
+1 to a message

I'm not sure if there is a legitimate case where a community PR could impact 50+ files.

I'd like a member of Core to review the PR and merged if it's truly OK.

**Comment by mkrizek** [comment]
Closing in favor of https://github.com/ansible/ansibullbot/pull/1033

**Pull request closed without merging**
