### PR TITLE
triage: commit after last comment scenario

### PR DESCRIPTION
**Pull request by resmo**
/cc @gregdek

### CODE REVIEW

**Comment by gregdek** [comment]
OK, so for clarity: is this for the "shipit but there have been edits so don't shipit" case?

And if so, should we be messaging this somehow?

**Comment by resmo** [comment]
@gregdek exaclty, That would make sense. 

E.g. Something like: 

"Thanks @{{ submitter }}, we see you did some work after the maintainers review. Therefore we put the PR back in community review. To the current maintainers, @{{ maintainer|join(', @') }} please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate."

**Comment by gregdek** [comment]
OK. If you can add that logic to this PR, I'll merge it. Thanks!

**Comment by resmo** [comment]
will rebase

**Comment by gregdek** [comment]
Still a little confused here, so bear with me.

1. I still think we need separate boilerplate content for this, noting that we're putting it into *_review because the PR was changed. 

2. Would this apply to a PR that's already in shipit? Looking at #L333, wouldn't it just skip this entire path because the PR is already labeled shipit? Or is this PR not intended to handle that case?

**Comment by resmo** [comment]
1. Suggestions are very welcome, I am sure you find better words than I do.
2. We skip the maintainers L603 for shipits, but still handle the comments on L606.

**Comment by gregdek** [comment]
I think this still needs to point to the new boilerplate file, right? If this PR can use the messaging in comment 3, I think we're ready to go.

**Comment by resmo** [comment]
closing since this is not relevant anymore IMHO

**Pull request closed without merging**
