### PR TITLE
network/dnos10

### PR DESCRIPTION
**Pull request by gundalow**
We will shortly be getting Dell Networking modules, so set the maintainer. Peter and I wish to be informed of updates.

### CODE REVIEW

**Comment by gundalow** [comment]
@skg-net is there anyone that should be notified of changes to the Dell Network modules? If so please let us know their GitHub account and I'll add them

**Comment by skg-net** [comment]
Currently its only myself, is it possible to add company aliases?

**Comment by gundalow** [comment]
@skg-net Yes, just point me at the group in GitHub

**Comment by skg-net** [comment]
@gundalow Its a Dell mailing alias, its not a GitHub account. Is it ok?

**Comment by gundalow** [comment]
@skg-net I believe we only support GitHub accounts, so for the moment I'll add you in. Feel free to raisea PR if you have extra Dell employees that have GitHub accounts, or you end up with a Dell Organisation in GitHub

**Pull request merged**
