### PR TITLE
Add more logging for debugging of get_reviews

### PR DESCRIPTION
**Pull request by webknjaz**
Follow-up for #1077 + #1068

### CODE REVIEW

**Comment by webknjaz** [comment]
Oh, I thought @jctanner mentioned a relevant exception in slack. but it seems like it was this one.

**Comment by mkrizek** [comment]
sigh, this happened again (after 14 days???). Can you please fix the test failure (I suspect by rebasing)? Thanks!

**Comment by webknjaz** [comment]
Sure :)

**Comment by webknjaz** [comment]
I think tests fail because the module has been moved in the core repo:
```console
>           self.assertEqual(EXPECTED, res)
E           AssertionError: Lists differ: ['lib/ansible/modules/messaging/rabbitmq_plugin.py'] != ['lib/ansible/modules/messaging/rabbitmq/rabbitmq_plugin.py']
E           
E           First differing element 0:
E           'lib/ansible/modules/messaging/rabbitmq_plugin.py'
E           'lib/ansible/modules/messaging/rabbitmq/rabbitmq_plugin.py'
E           
E           - ['lib/ansible/modules/messaging/rabbitmq_plugin.py']
E           + ['lib/ansible/modules/messaging/rabbitmq/rabbitmq_plugin.py']
E           ?                                         +++++++++
```

**Comment by webknjaz** [comment]
I've corrected the expected result in tests

**Pull request merged**
