### PR TITLE
WIP: Notify namespace maintainers sooner and notify fewer maintainers

### PR DESCRIPTION
**Pull request by pilou-**
When there is only one module maintainer (pull request is related to an existing module) or when pull request is about a new module:
- notify namespace maintainers even if module maintainer didn't approve the pull-request using `shipit`
- notify fewer namespace maintainers (at most 3).

I would like this pull requests to be discussed with community working group:
- more or less namespace maintainers could be notified
- different number of namespace maintainers could be notified
  - for existing module with only one maintainer
  - for new module

### CODE REVIEW

**Comment by pilou-** [comment]
cc @gregdek

**Comment by pilou-** [comment]
Note for myself, check that:
- submitter is not contained in maintainers variable (or remove it) in order to avoid [this](https://github.com/ansible/ansible/pull/21542#issuecomment-318228381).
- when there isn't any other namespace maintainer

**Comment by gregdek** [comment]
Here's my concerns: 

1. Right now, either a maintainer wants to be a responsible party, or they don't. There's kind of no in-between. 

2. We also have no good way of choosing "which n" maintainers get notified. The first n? The last n? A random selection of n? 

@pilou- what's your specific concern? Are you yourself receiving too many notifications?

**Comment by pilou-** [comment]
My specific concern: how can we decrease number of open pull requests? how could pull requests be reviewed faster?

1. when there is only one module maintainer, I want to notify some namespace maintainers sooner (I mean: at the same time the single module maintainer is notified, not after the single module maintainer had approved) because their reviews are required (in fact there is one case when their reviews won't be required: if the single module maintainer and 3 other people approved the pull-request).

2. On the other hand, I am not sure if many namespace maintainers notified (an example [here](https://github.com/ansible/ansible/pull/27245#issuecomment-317481290)) is a good thing.

About your 2nd point: a random selection of n looks good to me.

**Comment by jctanner** [comment]
1. I have no problem with people being pinged earlier, but I wouldn't count on that increasing the amount of reviews given. There's already a large set of labels that categorize the issues+pulls, so maintainers no longer have an excuse to not look at them other than being busy or absent. Notifying them won't change their availability.

2. If people don't want to be notified, they can opt out of maintainership.

**Comment by mscherer** [comment]
Github notifications are kinda bad however, to the point of featuring projects like octobox ( https://github.com/octobox/octobox ) on the explore page ( https://github.com/showcases/tools-for-open-source ). 

And as for notifying less maintainers, there is psychological research that tend to lead credence to the idea (e.g. Social Proof and Bystander Effect). If we notify 10 people 10 times for 10 bugs, they will likely all think someone else will deal with it, while notifying only one or two peoples would tell them "that's up to you". It may indeed not result into better results, but it can't make things worst IMHO. 

That's also how rust-highfive work ( https://huonw.github.io/blog/2015/03/rust-infrastructure-can-be-your-infrastructure/ ), and Sarah Sharp work on the topic show this did improve things: http://sarah.thesharps.us/2016/11/17/impact-of-bots-on-github-communities/

In a ideal world also, notifying people in smaller batch would help to see who answer and who don't, and then would give us data on who is more reactive, and help find place where there is a maintenance gap.

**Comment by gregdek** [comment]
The presence of "too many reviewers" is a potentially real problem. One potentially policy remedy is to cut down the max number of active reviewers to, say, 3. 

But I think the real remedy lies elsewhere. I think we're already doing plenty to encourage our community to review module PRs -- and the fact is that some of them may simply not want to do it. Which means that what we *really* need, IMO, is a better mechanism to flag modules that are not being well-maintained.

Anyway, I don't think this is a tooling issue. I think it's a process issue. We need to sort out process changes we need to make, and then make the tools fit them, not vice versa. For that reason, I'm -1 on this PR.

**Comment by gundalow** [comment]
@pilou- What are your thoughts with this?

**Comment by mkrizek** [comment]
Closing this as there are no modules namespaces since ansible/ansible#68966

Thanks @pilou- !

**Pull request closed without merging**
